[config]
chrome_cache = "./chrome"
chrome_version = "1336641"
output_pdf = "features-and-procedures-guide.pdf"
url = "http://localhost:5173"
vitepress_links = [
    ".vitepress/toc_links.json",
    ".vitepress/features_guide_links.json",
    ".vitepress/procedures_guide_links.json"
]

[config.print_to_pdf]
generateDocumentOutline = true
paperHeight = 11.7 # A4 page
paperWidth = 8.3
printBackground = true