name: Build n Test

on:
  pull_request:
  push:
    branches:
      - main
      - "ES*"
  workflow_dispatch:

defaults:
  run:
    shell: bash -eux {0}

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo build
        run: cargo build --release
      
      - run: zip -j vitepress-pdf-export_macos.zip ./target/release/vitepress-pdf-export
      
      - uses: actions/upload-artifact@v4
        with:
          name: vitepress-pdf-export_macos
          path: |
            ./vitepress-pdf-export_macos.zip
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo build
        run: cargo build --release

      - run: zip -j vitepress-pdf-export_linux.zip ./target/release/vitepress-pdf-export
      
      - uses: actions/upload-artifact@v4
        with:
          name: vitepress-pdf-export_linux
          path: |
            ./vitepress-pdf-export_linux.zip
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [build-mac, build-linux]
    steps:
      - uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vitepress-pdf-export_macos.zip
            vitepress-pdf-export_linux.zip

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo test
        run: cargo test --locked
